name: Demo
on: push
jobs:
    publish-demo:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: peaceiris/actions-gh-pages@v3
            with:
                allow_empty_commit: true
                enable_jekyll: true
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: demo
